workflow changes

diff --git a/.github/workflows/docker-build-push.yml b/.github/workflows/docker-build-push.yml
--- a/.github/workflows/docker-build-push.yml
+++ b/.github/workflows/docker-build-push.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - production
     paths-ignore:
-      - .github/workflows/docker-build-push.yml
+      - .github/workflows/docker-build-push.yml # Ignore changes to this specific YAML file
 
 jobs:
   build:
@@ -15,10 +15,14 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v2
 
+      - name: List Files in the Repository
+        run: |
+          ls -la  # List all files to verify Dockerfile location
+
       - name: Build Docker Image
         id: build
         run: |
-          docker build -t suyogborael796/browser-elaunch:latest .
+          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/browser-elaunch:latest . || { echo "Docker build failed"; exit 1; }
 
       - name: List Docker Images
         run: |
@@ -26,7 +30,7 @@ jobs:
 
   push:
     runs-on: ubuntu-latest
-    needs: build
+    needs: build # Ensure that the build job completes before this job starts
 
     steps:
       - name: Log in to Docker Hub
@@ -37,4 +41,4 @@ jobs:
 
       - name: Push Docker Image
         run: |
-          docker push suyogborael796/browser-elaunch:latest
+          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/browser-elaunch:latest
